### ISSUE TITLE
New scenarios?

### ISSUE THREAD

**Issue by BackSpace54** [a2-4am/wizard-replay#2]
Hi,
once again great pack for a legendary CRPG game (an emblematic one for sure).
Is there any possibility to add those Wiz#1 scenarios:
- https://zimlab.com/wizardry/mods/dragonquest.htm
- https://zimlab.com/wizardry/mods/weeping_snows.htm
- https://zimlab.com/wizardry/mods/blackstone.htm
- https://zimlab.com/wizardry/mods/atomic.htm
- https://zimlab.com/wizardry/mods/fineousrevenge.htm
Best regards.

**Comment by a2-4am** [comment]
Snafaru has requested we not include Dragonquest yet because of in-progress revisions. We have the others on our radar for v2.

**Comment by peterferrie** [comment]
We've added the ones that we liked in 2b4b6c150451133123d1bb77c9c25b81e1fc84fd.  We're not considering any others right now.
