### ISSUE TITLE
Games won't launch on Virtual II

### ISSUE THREAD

**Issue by quentinnuk** [a2-4am/wizard-replay#3]
Archive.org hdv disk boots fine and the scenario menu appears, but the games dont launch beyond the initialisation of the screen (where they used to load system.apple IIRC). The display hangs with just the steady cursor in the top left, it does not display the "PREPARE YOURSELF..." text.

Virtual ][ 11.4 emulating: Apple //e with SCSI card in slot 6 (to attached hdv), 64K plus 64K RAMWorks extension in aux slot, a single disk ][ in slot 5.

Ive tried it without the 64K aux RAM, and have the same issue.

I will also raise an issue with Virtual ][ support, to see if its that end.

**Comment by frankmilliron** [comment]
Try moving the SCSI to slot 7 and add a Disk II to slot 6. I believe this has been fixed in the code.

**Comment by a2-4am** [comment]
Frank is correct that the release version has a bug where the games still expected a Disk II in slot 6 (fixed in https://github.com/a2-4am/wizard-replay/commit/7d4206ed2e9924acf3a40cd0707def9bb40f74c1 but unreleased). Let me know if his workaround works for you.

**Comment by quentinnuk** [comment]
Yes the work around worked, thanks!

**Comment by a2-4am** [comment]
Thanks. I'll close this then. We're planning a new release soon-ish!
