### ISSUE TITLE
Wizard Replay menu shows Ultima 1-5 and Ultimore Scenarios

### ISSUE THREAD

**Issue by wyatt-wong** [a2-4am/wizard-replay#4]
Why do Wizard Replay menu shows Ultima 1-5 and Ultimore Scenarios but there is nothing inside ?

<img width="1366" alt="Screenshot 2024-06-30 at 12 33 20 AM" src="https://github.com/a2-4am/wizard-replay/assets/10095648/979a0e7c-e569-4788-8ab2-870e59cdbd66">
<img width="1366" alt="Screenshot 2024-06-30 at 12 34 15 AM" src="https://github.com/a2-4am/wizard-replay/assets/10095648/3feef6bb-a51e-478c-992a-94330cf342d2">

**Comment by peterferrie** [comment]
Because they are not added yet.
